version: '3.8'

services:
  mysql:
    image: mysql:8.0.32
    container_name: mysql_container
    restart: always
    env_file: 
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "33333:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "${DB_HOST}", "-u${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_container
    restart: always
    working_dir: /app
    command: >
      sh -c "sleep 10 &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: 
      - .env
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
    driver: local
