# Generated by Django 5.1.3 on 2025-02-20 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmenttest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appointmenttest',
            name='updated_at',
        ),
    ]
